Meteor.methods({
  searchProducts: function(term) {
    var autocompleteList, searchResults;
    check(term, String);
    searchResults = ReactionCore.Collections.Products.find({
      title: {
        $regex: ".*" + term + ".*",
        $options: "i"
      }
    }, {
      fields: {
        _id: 1,
        title: 1,
        variants: 1
      }
    });
    autocompleteList = [];
    searchResults.forEach((function(product) {
      var listItem;
      listItem = {
        value: product.title,
        id: product._id,
        price: product.variants[0].price
      };
      return this.push(listItem);
    }), autocompleteList);
    return autocompleteList;
  },
  searchProductsByDate: function(date) {
    var autocompleteList, isoDate, searchResults;
    check(date, String);
    isoDate = new Date(date);
    ReactionCore.Log.info("searching prods with date: ", isoDate);
    searchResults = ReactionCore.Collections.Products.find({
      forSaleOnDate: isoDate
    }, {
      fields: {
        _id: 1,
        title: 1,
        variants: 1
      }
    });
    autocompleteList = [];
    searchResults.forEach((function(product) {
      var listItem;
      ReactionCore.Log.info("prod found for date: ", product.title);
      listItem = {
        value: product.title,
        id: product._id,
        price: product.variants[0].price
      };
      return this.push(listItem);
    }), autocompleteList);
    return autocompleteList;
  }
});

// ---
// generated by coffee-script 1.9.2
