ReactionCore.registerPackage({
  name: "reaction-search",
  provides: ['Search'],
  label: "Search",
  description: "Search Package for Reaction Commerce",
  icon: "fa fa-search",
  autoEnable: true
});

// ---
// generated by coffee-script 1.9.2
